AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Automated process for keeping manual snapshots on aurora

Parameters:
  ClusterId:
    Type: String
    Description: The name of the Aurora Cluster to be snapped
  Chron:
    Type: String
    Description: Chron schedule
    Default: rate(7 days)
  TTLMetric:
    Type: String
    Description: Unit for time to live [Ex -> Second | Minute | Hour | Day | Month]
    Default: Month
  TTL:
    Type: Number
    Description: Number of units for TTL
    Default: 12
  BrodcastOnSuccess:
    Type: String
    Description: Broadcast to SNS Topic on successful snapshots
    Default: false

Globals:
  Function:
    Runtime: nodejs8.10
    MemorySize: 128
    Timeout: 300
    Environment:
      Variables:
        SNS_TOPIC_ARN: !Ref SNSBroadcast
        CLUSTER_ID: !Ref ClusterId

Resources:
  # SNS Topic for notifications
  SNSBroadcast:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: AuroraSnapperBroadcast


  # Policy to create logs if needed
  SnapperManagedLogPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: '*'

  # Policy to access RDS
  SnapperManagedAuroraPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - rds:CreateDBClusterSnapshot
              - rds:DeleteDBClusterSnapshot
              - rds:DescribeDBClusterSnapshots
            Resource: '*'
  
  SnapperManagedSQSPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sns:Publish
            Resource: !Ref SNSBroadcast

#########################
## Duplicate as needed ##
#########################
  SnapperLambda24Hour:
    Type: 'AWS::Serverless::Function'
    Properties:
      Policies:
        - !Ref SnapperManagedLogPolicy
        - !Ref SnapperManagedAuroraPolicy
        - !Ref SnapperManagedSQSPolicy
      Handler: snapper/index.handler
      Events:
        CreateAuroraSnapshot:
          Type: Schedule
          Properties:
            Schedule: !Ref Chron
      Environment:
        Variables:
          TIME_TO_LIVE: !Ref TTL
          TIME_TO_LIVE_METRIC: !Ref TTLMetric
          BROADCAST_ON_SUCCESS: !Ref BrodcastOnSuccess

Outputs:
  BroadcastTopicArn:
    Description: 'SNS Topic Arn for subscriptions for notifications'
    Value: !Ref SNSBroadcast